//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managament_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE
    {
        public int FEESID { get; set; }
        public int STUDENTID { get; set; }
        public Nullable<int> Amount { get; set; }
        public System.DateTime FeesPaidDate { get; set; }
        public System.DateTime Lastdate { get; set; }
        public Nullable<int> Penelty { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
