//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managament_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PARENT
    {
        public int PARENTSID { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "The {0} value cannot exceed {1} characters. ")]
        [DataType(DataType.Text)]
        [RegularExpression("^([a-zA-Z]+[a-zA-Z])$", ErrorMessage = "Invalid First Name, Only Enter Alphabet Letter")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "The {0} value cannot exceed {1} characters. ")]
        [DataType(DataType.Text)]
        [RegularExpression("^([a-zA-Z]+[a-zA-Z])$", ErrorMessage = "Invalid Last Name , Only Enter Alphabet Letter")]
        public string LastName { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\.]+@[a-z\.]+\.[com,in,co].{0,3})$", ErrorMessage = "Invalid Email ID, Format : example@gmail.com ")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(?:(?:\+|0{0,2})91(\s[\-]\s)?|[0]?)?[6789]\d{9}$", ErrorMessage = "Invalid Contact no, Only Enter Number")]
        public string Contactno { get; set; }
        [Required]
        public Nullable<int> STUDENTID { get; set; }
        [Required]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$ %^&*-]).{8,}$", ErrorMessage = "Password Should be 8 characters long ,At list 1 uppercase char, 1 lowercase char , 1 number , 1 Special Char(#?!@$ %^&*-).")]

        public string Password { get; set; }

        public virtual Student Student { get; set; }
    }
}
