//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_Managament_System_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentEntry
    {
        public int ID { get; set; }
        public string StudentName { get; set; }


        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }
        [DataType(DataType.Time)]
      

        public Nullable<System.TimeSpan> OUTTIME { get; set; }
        [DataType(DataType.Time)]

        public Nullable<System.TimeSpan> INTIME { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> STUDENTID { get; set; }
    }
}
